---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# .. Copyright (C) 2022 VEXXHOST, Inc.
# .. SPDX-License-Identifier: Apache-2.0

# Default variables
# =================

# .. contents:: Sections
#    :local:


# .. envvar:: openstack_helm_octavia_chart_repo_name [[[
#
# Helm repository name for the chart.
openstack_helm_octavia_chart_repo_name: openstack-helm

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_chart_repo_url [[[
#
# Helm repository URL for the chart.
openstack_helm_octavia_chart_repo_url: https://tarballs.opendev.org/openstack/openstack-helm/

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_chart_name [[[
#
# Helm chart name (will also be used for release name)
openstack_helm_octavia_chart_name: octavia

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_image_repository [[[
#
# Image repository location to be prefixed for all images
openstack_helm_octavia_image_repository: "{{ atmosphere_image_repository | default('us-docker.pkg.dev/vexxhost-infra/openstack') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_image_tag [[[
#
# Image tag for container
openstack_helm_octavia_image_tag: wallaby

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_heat_image_tag [[[
#
# Image tag for Heat to be used for jobs running via Helm hooks
openstack_helm_octavia_heat_image_tag: wallaby

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_neutron_image_tag [[[
#
# Image tag for Neutron to be used for openvswitch_vswitchd
openstack_helm_octavia_neutron_image_tag: 18.2.1.dev7-6

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_values [[[
#
# Overrides for Helm chart values
openstack_helm_octavia_values: {}

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_images [[[
#
# List of images to provision inside OpenStack
openstack_helm_octavia_images: []

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_heartbeat_key [[[
#
# Heartbeat key
openstack_helm_octavia_heartbeat_key: "{{ undef(hint='You must specify a Octavia heartbeat key') }}"

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_health_manager_nodes [[[
#
# List of FQDNs for node names that run the health manager
openstack_helm_octavia_health_manager_nodes: []

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_management_subnet_cidr [[[
#
# Octavia management subnet (CIDR)
openstack_helm_octavia_management_subnet_cidr: "172.24.0.0/22"

                                                                   # ]]]
# .. envvar:: openstack_helm_octavia_amphora_image_url [[[
#
# Octavia amphora image url
openstack_helm_octavia_amphora_image_url: "https://tarballs.opendev.org/openstack/octavia/test-images/test-only-amphora-x64-haproxy-ubuntu-focal.qcow2"

                                                                   # ]]]
